# Dockerfile

# without an file extension

# Use an official Python runtime as a parent image 
FROM scatterlab/mecab-ko 
#estate_model:latest




 # Set the working directory to /app 
WORKDIR /app 



 # Copy the current directory contents into the container at /app 
COPY . /app  



# Install any needed packages specified in requirements.txt 
RUN pip install --trusted-host pypi.python.org -r requirements.txt 



# Make port 80 available to the world outside this container 
EXPOSE 5000



 # Define environment variable 
ENV NAME World 


CMD ["python", "was.py"]
